### PR TITLE
Ran FindBugs on Vanilla

### PR DESCRIPTION
**Pull request by TomyLobo**
The hashCode methods might break some things, so they need to be tested before pushing them

The changes from the last commit should not be pulled, but inspected by the respective developers.
I didn't sign off the last commit to hint at this.

I also made one for SpoutAPI: https://github.com/SpoutDev/SpoutAPI/pull/230
and one for Spout:https://github.com/SpoutDev/Spout/pull/1894

### CODE REVIEW

**Comment by windy1** [comment]
You're going to have to rebase :)

**Comment by windy1** [comment]
It looks good but I'll leave this to @NinjaZidane to pull because of some potential breaking changes.

**Comment by ZNickq** [comment]
@W1ndwaker This isn't supposed to be pulled :P We can just look through the diffs and fix the small bugs, FindBugs is really great ^^

**Comment by windy1** [comment]
@ZNickq Yes, I'm aware of that now :p

**Comment by Salynne** [comment]
Closing these, and making some probably permanent issues for the repos as a reminder to keep up to date on this.

http://issues.spout.org/browse/VANILLA-137

**Pull request closed without merging**
