### PR TITLE
Fixed some buffer lengths, added UseBedCodec and UseBedMessage for packe...

### PR DESCRIPTION
**Pull request by Darsstar**
...t 0x11 and some cleanup

I checked every packet listed [here](http://wiki.vg/Protocol) for the right buffer lengths and if the right values where read/writen. I hope I got them all, but who knows...

### CODE REVIEW

**Comment by RoyAwesome** [comment]
RoyAwesome: Darsstar tested?
 Darsstar: it compiles and i did not get my client/server to crash
 RoyAwesome: actually, you are going to hate me for this
 RoyAwesome: but
 Darsstar: _hates you_
 RoyAwesome: can you write tests to ensure that they are encoded and decoded properly?
 RoyAwesome: This seems like a good chance to start getting some test coverage on our networking side
 Darsstar: yes, I can
 Darsstar: but it will have to wait till tomorrow
 RoyAwesome: ok
 Darsstar: almost off to bed now
 RoyAwesome: alright
 RoyAwesome: add them to that pull
 Darsstar: ok
 Darsstar: are you placing a comment not to pull it untill I added tests, or should I?
 RoyAwesome: yeah, I'll do it
 Darsstar: ok`

**Comment by zml2008** [comment]
I'm writing some tests for the protocol from some plans I put together a while ago and will merge this with those tests.

**Comment by Darsstar** [comment]
@zml2008 meaning I don't have to? I am willing to help.

**Comment by zml2008** [comment]
I'll push what I'm working on once I'm done and you can file a PR with any suggestions for improvement you have.

**Comment by zml2008** [comment]
So I'm nearly done with the tests, I think I found an issue with ChannelBufferUtils.writeParameters() that will need to be fixed though.

**Pull request closed without merging**
