### PR TITLE
Fixed respawn code.

### PR DESCRIPTION
**Pull request by Pamelloes**
Players will now respawn correctly :D
Signed-off-by: Pamelloes joshua314@sbcglobal.net

### CODE REVIEW

**Comment by windy1** [comment]
Needs to be rebased before it can be pulled.

**Comment by Pamelloes** [comment]
bu.... bu..... bu...... I have no idea how to do that :(

**Comment by windy1** [comment]
`git remote add upstream git@github.com:VanillaDev/Vanilla.git
git fetch upstream
git merge upstream/master
git push origin master`

Should do it

**Comment by windy1** [comment]
This fail was my fault for giving poor instructions, sorry about that.

**Pull request merged**
