### PR TITLE
Added sheep shearing.

### PR DESCRIPTION
**Pull request by spacechase0**
The sheep don't update client-side as sheared, and the item data also isn't sent correctly to the client.

Signed-off-by: Chase W chasew@silkweaver.com

### CODE REVIEW

**Comment by windy1** [comment]
Looks good to me @NinjaZidane :)

I'm guessing the updating client side is Spout not updating the entity data correctly?

**Comment by Zidane** [comment]
Is it just me or is @spacechase0 's obession with sheep...spooky.

**Comment by Darsstar** [comment]
Not just you, my theory is that he will revert movement next to sent the sheeps to his alien overlords. I guess that technically makes me think his obsession with sheep is alien.

**Comment by spacechase0** [comment]
Sheep had several things needed doing. :P They have a lot more that need doing than, for example, pigs.

> I'm guessing the updating client side is Spout not updating the entity data correctly?
> Yes, at least as far as I know. It only sends those things in `getSpawnMessage`, and `getUpdateMessage` only sends `EntityTeleportMessage`.

One way I guess would be for `getUpdateMessage` to return a List (and change the name to plural :P), so that I could add a `EntityMetadataMessage`. Then `getSpawnParameters` could be renamed to `getMetadataParameters`, and that could be used for `getSpawnMessage`, too.

**Pull request merged**
