### PR TITLE
Some WGEN tweaks

### PR DESCRIPTION
**Pull request by DDoS**
Optimized the biome selector (AKA the noise selector), and renamed it to something more appropriate.

Also, I improved the smooth populator, but I'm keeping it deactivated for the moment as it doesn't behave properly with the ocean's ridiculous depth (I'll work on fixing those now). 

(and the "mark" method in the smooth populator can be ignored for the moment, it's just for testing purposes, I'll remove it later).

Signed-off-by: Aleksi Sapon QcTechs@gmail.com

### CODE REVIEW

**Comment by Zidane** [comment]
Rebase to head for me Aleksi.

**Comment by atheriel** [comment]
Aww... are you writing the ocean generator? I really wanted that one :(

**Comment by DDoS** [comment]
@atheriel I was just planing on fixing the depth, if you want to do generator, go ahead. I prefer tackling the nether anyway.

@NinjaZidane Tomorrow evening, I have to study for my math exam.

**Comment by windy1** [comment]
@DDoSQc gogogo! :D

**Pull request closed without merging**
