### PR TITLE
Vanilla now checks for the right protocol id, and only allows connecting if that matches!

### PR DESCRIPTION
**Pull request by ZNickq**

### CODE REVIEW

**Comment by Zidane** [comment]
I might have pulled this BUT we have been discussing allowing clients to connect on differening Vanilla protocol versions.

aka someone with Vanilla client 1.2 could play at the same time on the same server (running Spout 1.2 RB with Vanilla 1.2 RB) with a few people running 1.` or even 1.0 client.

**Comment by ZNickq** [comment]
I thought about that, but there are protocol differences which make that hard (1.2 has different chunk protocol, for example) and i'm not sure it could work without keeping the old code...

**Comment by Zidane** [comment]
Well we are gonna try ZNickq and see...unsure yet which way we are gonna head to.

**Comment by ZNickq** [comment]
well, this can just sit here in the meantime :)

**Comment by Afforess** [comment]
@NinjaZidane - I think I agree with @ZNickq on this one.

**Comment by Zidane** [comment]
With all the changes occurring to Minecraft 1.2....I am starting to agree as well. It might just be too difficult to put in backwards compatibility :/

So, in light of this I am gonna go ahead and merge this.

**Pull request merged**
