### PR TITLE
Make water and death stop burning

### PR DESCRIPTION
**Pull request by olliestanley**

### CODE REVIEW

**Comment by IronCrystal** [comment]
Glad you added this.

**Comment by Sleaker** [comment]
@DziNeIT - any reason the file looks like it was completely re-written?

**Comment by olliestanley** [comment]
I don't know. Probably fixed line endings or something (or maybe broken ones, idk anything about line endings)

**Comment by lukespragg** [comment]
Please check that you did not change the line endings to CRLF @DziNeIT. We can't really pull it in that state, as we can't tell what is changed easily.

**Comment by olliestanley** [comment]
Not gonna lie, I used the GitHub editor :P. In a bit I will pull it to local and amend the commit, bare with me

EDIT: Aww, I messed shit up. There will be a new PR in a few mins

**Pull request closed without merging**
