### PR TITLE
(squashed) Added PotionBrewEvent for when a potion has been brewed

### PR DESCRIPTION
**Pull request by timmhirsens**
fixed & squashed thehutch's PR

Signed-off-by:thehutch

### CODE REVIEW

**Comment by thehutch** [comment]
Thanks, also you should update this page: https://docs.google.com/spreadsheet/ccc?key=0AtJcLGogEpXCdGlrV2wySUhNNjJ2cC1zZE5YWEl6eGc#gid=0

**Comment by atheriel** [comment]
While you're at it, you can add that the ShearEntity event was implemented as well.

**Comment by windy1** [comment]
I don't have write access.

**Comment by dredhorse** [comment]
whats your googledocs account?

**Comment by windy1** [comment]
@dredhorse walkercrouse@gmail.com

**Comment by dredhorse** [comment]
done

**Pull request merged**
