### PR TITLE
Monsters equipping items

### PR DESCRIPTION
**Pull request by Sleaker**
Added new MonsterPickupitemComponent to handle logic for hostiles picking up inventory items they can wear.  Zombies, Skeletons, and PigZombies should now pickup items they walk over if they are better than items they currently have equipped, they will also pickup items into their held slot if nothing is equipped.

Signed-off-by: Nick Minkler sleaker@gmail.com

### CODE REVIEW

**Comment by Sleaker** [comment]
I'm not sure if it's correct to call the protocol event for the entity picking up the item. If this is incorrect please let me know.

**Comment by windy1** [comment]
Are inventories working for you atm? I've been having some issues with them.

**Comment by Sleaker** [comment]
@W1ndwaker - The Widget refactor broke changes being sent to players. Grinch tested it out pretty thoroughly, and they were working up until that commit.  So something in that refactor broke the client being sent updates.  He noticed that items are added/set server-side, but they aren't sent as updates to the player.  I threw a message to Karang since it looked like he had done a bit of the refactor and I'm really lost as to why a Widget refactor would break inventory changes being sent to the client.

**Comment by Afforess** [comment]
I can verify part of Sleaker's assertions, I have gone into debug mode and inventories themselves work (they collect, retain items and state correctly), but the changes are not being sent.

**Comment by Zidane** [comment]
@Sleaker is changing a few things for me, don't pull.

**Pull request merged**
