### PR TITLE
Added snow levels in code, and snow spm + Increased camera speed

### PR DESCRIPTION
**Pull request by SelennLamson**
Snow doesn't work at render, probably a problem with submaterials.
To fix asap.

Camera speed with the help of L5D, increased for the tests.

### CODE REVIEW

**Comment by DDoS** [comment]
You need to sign-off the commits

**Comment by windy1** [comment]
And squash 'em http://spout.in/pr

**Comment by LunNova** [comment]
The two commits aren't really related - shouldn't they be separate PRs, instead of squashing them?

**Comment by windy1** [comment]
@nallar As long as the description of the commit reflects all the changes one PR is fine.

**Comment by zml2008** [comment]
If the commits are not related they should be separate.

**Comment by windy1** [comment]
@zml2008 Not according to the current PR guidelines.

**Comment by zml2008** [comment]
Then you're interpreting the guidelines incorrectly. The guidelines mean
that you aren't supposed to have a ton of commits with things like "start
snow levels", "more snow levels", "fix some bugs with snow levels",
"snowlevelsaoeuoeu", not that everything should be blindly squashed into
one commit.

**Comment by windy1** [comment]
@zml2008 "Except in exceptional circumstances, each pull request should only be a single commit."

**Comment by LunNova** [comment]
Which doesn't mean that every change should be in one pull request.

**Comment by kitskub** [comment]
I don't see what the problem is. Each commit adresses completely diferent issues.  However, why make him make two different pull requests if they're both going to get pulled anyways?

**Comment by windy1** [comment]
No problem, it's just been standard ever since we enacted those PR guidelines to keep PRs to one commit.

**Comment by SelennLamson** [comment]
Sorry for signoff, i failed the commits and i didn't know how to change them.
If you tell me how to change these commits, i'll close this PR and do it again in the right way

**Pull request closed without merging**
