### PR TITLE
Added Versioning class to keep track of client/server compatibilities!

### PR DESCRIPTION
**Pull request by ZNickq**
:)

### CODE REVIEW

**Comment by zml2008** [comment]
Looks nice, but I'd prefer if some version checking were done in IdentificationCodec so the handler can be called even if the login packet is changed.

**Comment by ZNickq** [comment]
You mean inside the decode method? Sure, i'll change it after i finish my current task :)

**Comment by windy1** [comment]
"You mean inside the decode method? Sure, i'll change it after i finish my current task :)" - 4 days later. xD

I kid.

**Comment by Zidane** [comment]
Closing this....

Next time, please fix it up first before working on other stuff @ZNickq :p...when you push it to Vanilla make sure you cover what @zml2008 wanted as well.

**Pull request closed without merging**
