### PR TITLE
VanillaConfiguration and OpConfig now set the value of nodes to the valu...

### PR DESCRIPTION
**Pull request by Darsstar**
...e in config.yml and ops.yml respectively if it exists.

Signed-off-by:Darsstar darsstar@gmail.com

See https://github.com/SpoutDev/SpoutAPI/pull/142 and https://github.com/SpoutDev/Spout/pull/1801

### CODE REVIEW

**Comment by windy1** [comment]
This is unecassary. If the value is null it will fall back on the default value of the node which is defined in the constructor and through setDefaultValue()

**Comment by windy1** [comment]
Oh I see... If this is having a problem it needs to be done in SpoutAPI

**Comment by Zidane** [comment]
I will go ahead and pull this @W1ndwaker ...either of you are free to fix it in SpoutAPI and remove these two changes (referencing Spout as well).

**Comment by windy1** [comment]
The problem is that I was loading the node value before the config value and returning that. It needs to be the other way around, I'll fix it next chance I have.

**Comment by Darsstar** [comment]
Also the this pull (and the Spout one) rely on getNode() returning null not a Configuration node with the value null, which I changed in the SpoutAPI pull.
@W1ndwaker got any comments on the SpoutAPI pull?

**Pull request merged**
