### PR TITLE
Add HealthChangeReason.PLUGIN

### PR DESCRIPTION
**Pull request by kitskub**
SpoutAPI: https://github.com/SpoutDev/SpoutAPI/pull/469
Spout: https://github.com/SpoutDev/Spout/pull/2146
Signed-off-by: Jack Huey kitskub@gmail.com

### CODE REVIEW

**Comment by Zidane** [comment]
Can't be pulled

**Comment by kitskub** [comment]
Hmmm

**Comment by kitskub** [comment]
Updated :)

**Comment by windy1** [comment]
I don't see the need for this, I think plugin causes can just go under UNKNOWN

**Comment by kitskub** [comment]
But, it's not unknown. It's a plugin.

**Comment by dredhorse** [comment]
I think this is useful, we also have a plugin cause in spout api.

**Pull request merged**
