### PR TITLE
Added "/Ping" Command

### PR DESCRIPTION
**Pull request by emericask8ur**
-Added /Ping Command
-Checks if Player is Source

https://github.com/emericask8ur/Vanilla/commit/e1554de4897654f377f6c4670e4a3be99f54f978

Signed Off by emericask8ur sk8tj@yahoo.com

### CODE REVIEW

**Comment by ZNickq** [comment]
Squash em!

**Comment by emericask8ur** [comment]
Hehe ^^

**Comment by Top-Cat** [comment]
And remember to sign the squashed commit, only 1/3 of these are

**Comment by lukespragg** [comment]
I don't really like the usage description. It's a little sloppy compared to the rest and the capitalization of the P is a little silly. :P

**Comment by Zidane** [comment]
Closing this

I appreciate this @emericask8ur but I feel this command doesn't quite belong within Vanilla. It would better fit in a plugin such as CommandBook or Essentials (whenever they port to Spout).

**Comment by emericask8ur** [comment]
Ill give ya that one Ninja..

**Pull request closed without merging**
