### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by igniansoft**
Just fixed one line of spacing because it was wierd looking ;) - Guy_de_Siguro

### CODE REVIEW

**Comment by igniansoft** [comment]
uuuh fail :(

**Comment by Zidane** [comment]
:S

**Comment by igniansoft** [comment]
I know :P, I noticed afterwards that it was not necessary nor was it different to the other spacings :(

**Comment by lukespragg** [comment]
/me pulls out knife and waves it around at people trying to touch his pom.

**Comment by igniansoft** [comment]
Well it would be nicer if it had breaks before each comment maybe ;)

**Pull request closed without merging**
