### PR TITLE
Added minecart physics

### PR DESCRIPTION
**Pull request by bergerkiller**
Signed-off-by: berger killer bergerkiller@gmail.com

Part is still under development for a bit, but the main core is finished. It adds several functions extending classes can override to handle velocity modifiers, and others. The only thing that needs to be done is having 'y-snap' (snap to correct Y position) and some debugging.

### CODE REVIEW

**Comment by Top-Cat** [comment]
There's a few spaces hanging around (need to be tabs) and not signed

**Comment by bergerkiller** [comment]
Sec I'll fix it really quick...

EDIT

This should fix it...though I fail to sign of this PR itself.

**Comment by Top-Cat** [comment]
Signed, but still got spaces

**Comment by bergerkiller** [comment]
But where?! I did a global '    ' search and found none :/

**Comment by Top-Cat** [comment]
http://i.imgur.com/xfZgs.png

**Comment by bergerkiller** [comment]
Ok hopefully it is now fixed? xd

**Pull request closed without merging**
