### PR TITLE
Added entity ID <-> Class mappings.

### PR DESCRIPTION
**Pull request by spacechase0**
I'm using this for Spawn Eggs. I only did mobs, though, because I wasn't sure about some (like Minecart, three different controllers for one ID).

Signed-off-by: Chase W chasew@silkweaver.com

### CODE REVIEW

**Comment by windy1** [comment]
Can we use imports please?

**Comment by spacechase0** [comment]
I was going to, but too many of them had the same name for the enum and for the import. Creeper, Spider, Sheep, etc.

**Comment by spacechase0** [comment]
Okay, done.

**Comment by Darsstar** [comment]
https://github.com/SpoutDev/Vanilla/pull/68 (A)

**Comment by Zidane** [comment]
.

**Comment by Zidane** [comment]
@Darsstar actually took what you did and simply fixed it up a little. Thanks for the initial pull @spacechase0  !

**Pull request closed without merging**
