### PR TITLE
Added a NetBeans license hint to the pom

### PR DESCRIPTION
**Pull request by Darsstar**
see http://wiki.netbeans.org/MavenBestPractices#License_Header

Is this this @Wulfspider approved?

### CODE REVIEW

**Comment by ZNickq** [comment]
The formatting is wrong ;)

**Comment by Darsstar** [comment]
Maybe I should have waited until class was over and pay more atention to both things. If this train would let my laptop onto the network I could fix it right now...

**Comment by Darsstar** [comment]
It is now indented with tabs instead of spaces like the the poms of Spout and SpoutAPI

**Comment by lukespragg** [comment]
This isn't really necessary, being as we may be pushing project files for each. This entry in the pom would only apply to anyone who actually manually made that license in their IDE, so a full project file would be better.

**Pull request closed without merging**
