### PR TITLE
Fix Hunger Related Bugs.

### PR DESCRIPTION
**Pull request by MWisBest**
Fix player spawning with 0 health. Fix creative players getting hunger related damage.

### CODE REVIEW

**Comment by windy1** [comment]
Thanks :)

**Comment by ZNickq** [comment]
@W1ndwaker you do know that we are not supposed to handle PRs, right? ;P

**Comment by windy1** [comment]
@ZNickq I had a chat with @NinjaZidane 

Me and you are allowed to handle the smaller ones, talk to Zidane about it.

**Comment by ZNickq** [comment]
Sweet :D

**Pull request merged**
