### PR TITLE
Move more inventory events

### PR DESCRIPTION
**Pull request by Sleaker**
Signed-off-by: Sleaker sleaker@gmail.com

### CODE REVIEW

**Comment by Afforess** [comment]
Why was this pulled? Empty classes/interfaces screams bad design.

**Comment by Zidane** [comment]
@Afforess they are stubs for now :P

**Comment by Afforess** [comment]
Then add them when you need them. They serve no purpose.

**Comment by Sleaker** [comment]
@Afforess - I was told nothing in API can reference classes in the plugin package, to be able to move anything over to API (see events), these have to be housed in the API (and anything they reference), not in the plugin.  I don't see a way around that without having intermediate classes that serve as the API reference, or just moving everything around so it makes no difference which package it is in.

**Pull request merged**
