### PR TITLE
Implemented the smooth populator

### PR DESCRIPTION
**Pull request by DDoS**
It's gonna need more tweaking, but that's hard to do without proper biomes, and currently the world generated seems to be only one large biome.

It's a start at least.

Signed-off-by: Aleksi Sapon QcTechs@gmail.com

### CODE REVIEW

**Comment by zml2008** [comment]
imo the smoothing populator should be implemented as a normal populator not connected to a specific biome, run before the BiomeDecorators. This can be done within BiomeGenerator.

**Comment by DDoS** [comment]
I was told to do it like this.

**Comment by zml2008** [comment]
When we discussed this a few months ago we decided on the layout I described in my original comment, and I don't remember that decision changing. This is also where biome smoothing is placed in http://forums.spout.org/threads/a-look-at-vanilla-world-generation.1780/

**Comment by Zidane** [comment]
I thought this was the best approach to it...didn't even think about doing it within the BiomeGenerator. @zml2008 is on to something here.

**Comment by Zidane** [comment]
Yeah I admit this was my bad...I completely forgot about that. Thanks for letting us know @zml2008

**Comment by DDoS** [comment]
Well, I guess I better close this.

**Comment by Zidane** [comment]
@DDoSQc you can still adapt this easily to the BiomeGenerator :).

**Comment by DDoS** [comment]
Yeah, once I'm done fighting my way through git, I'll have make a PR. I also added a addPopulator method to the BiomeGenerator.

**Pull request closed without merging**
