### PR TITLE
Some API refactoring. I may have missed some.

### PR DESCRIPTION
**Pull request by greatman**
Signed-off-by: William Lebel lebelwilliam@gmail.com

### CODE REVIEW

**Comment by Zidane** [comment]
API can't depend on Plugin.

You moved stuff to API that is still in worlds.

Hint: VanillaGenerators.

**Comment by greatman** [comment]
Updated it. Should be good now.

**Comment by windy1** [comment]
Needs a rebase

**Comment by greatman** [comment]
rebased.

**Comment by Zidane** [comment]
rebase again!

**Comment by greatman** [comment]
Rebased ;)

**Comment by Afforess** [comment]
rebase again!

**Comment by greatman** [comment]
Stop breaking mah refactor D=

**Comment by greatman** [comment]
And updated.

**Pull request merged**
