### PR TITLE
Fixed Chests

### PR DESCRIPTION
**Pull request by kitskub**
This pull WAS going to be to fix Block Components. But I'm now going to fix chests.

Fixes: http://issues.spout.org/browse/VANILLA-199

Signed-off-by: Jack Huey kitskub@gmail.com

### CODE REVIEW

**Comment by windy1** [comment]
Is this actually working? Wasn't sure if block components had been implemented completely yet.

**Comment by kitskub** [comment]
Well, it at least doesn't do this: http://issues.spout.org/browse/VANILLA-199

**Comment by windy1** [comment]
Okay, well, I'm not sure if the implementation in SpoutAPI is even correct. Why don't we have Block implement ComponentHolder @Zidane?

**Comment by kitskub** [comment]
I think it's because each block should only have one component, but ComponentHolder allows multiple.

**Comment by windy1** [comment]
Why should Blocks be limited to one Component? I can't think of a reason.

Blocks should however be limited to one **Entity** I think.

**Comment by kitskub** [comment]
Not sure, but that's what the current code is saying.

**Comment by kitskub** [comment]
If it helps anything, I'm working on adding back in entity-->block interaction. I can add to this pull or put it in a separate one.

**Comment by kitskub** [comment]
Oh, it doesn't work after a server restart. This is probably due to the entity not saving, rather than the component not being set.

**Comment by Afforess** [comment]
> Why should Blocks be limited to one Component? I can't think of a reason.

Why should they have more than one? They are limited to one material.

This pull is needed anymore due to changes in how I implemented BlockComponents.

**Comment by kitskub** [comment]
Ok, the vanilla pull is not needed, but I think at least part of the SpoutAPI and/or Spout pull still is. Also, shouldn't ComponentMaterial be removed?

**Comment by windy1** [comment]
@kitskub @Afforess is redoing the design entirely so the Spout PRs will likely be invalid as well :/

**Comment by kitskub** [comment]
@W1ndwaker me and Afforess talked. I'm going to update all the pulls to fit current specifications. Please reopen.

**Comment by Afforess** [comment]
Vanilla Team: Do not pull w/o talking to me first. I am still changing Block Components even more.

**Comment by kitskub** [comment]
No longer needed because of https://github.com/VanillaDev/Vanilla/commit/2aa712b29d88c1f6444ab0d734731f44ce0de6d

**Pull request closed without merging**
