### PR TITLE
Fix JavaDoc wording for Ping.java

### PR DESCRIPTION
**Pull request by olliestanley**
Couldn't stop myself when I saw it :P

### CODE REVIEW

**Comment by windy1** [comment]
Sorry, but please don't open PRs for JavaDoc only changes. Either include it in another PR or just point it out to a team member.

**Comment by olliestanley** [comment]
If you're going to have silly rules like that, they should at least be on spout.in/prguide so people actually know.

**Comment by lukespragg** [comment]
It's the first I've heard of it. It's not a rule that I've approved though.

Generally it's more of the point the size, not that it's a doc PR.

**Comment by lukespragg** [comment]
To add to my previous reply, we do accept Javadoc pull requests, but I'd
recommend putting more effort into making it have more substance, else just
mention the issue to a staff member if it's minor.

**Comment by olliestanley** [comment]
Fair enough, but the size point should still be added to the pr guide.

**Comment by lukespragg** [comment]
The whole doc needs to be redone honestly. One of the things on my todo
lost.

**Pull request closed without merging**
