### PR TITLE
Added sensible default getDrops implementation to reduce code duplication.

### PR DESCRIPTION
**Pull request by LunNova**
Note: code duplication not actually removed yet, this just makes it possible.

Signed-off-by: nallar rallanpcl@gmail.com

### CODE REVIEW

**Comment by Zidane** [comment]
rebase for me @nallar

**Comment by LunNova** [comment]
I thought we decided in #Vanilla that this way didn't allow enough and would still require overriding getDrops in too many cases, and I still haven't finished the other way.

**Comment by Zidane** [comment]
Erm that is correct @nallar ...want to close this or still use it?

**Comment by windy1** [comment]
I don't really see any other way, if you need to add on to this you could just override it and make sure you call super#getDrops

**Comment by LunNova** [comment]
@W1ndwaker 

This doesn't allow for multiple drops or random numbers of drops, and that would be possible.

**Comment by windy1** [comment]
Alright, I'm going to go ahead and close it then.

**Pull request closed without merging**
