### PR TITLE
Added functionality to get the spawnpoint and to get the sky from  worldgen.

### PR DESCRIPTION
**Pull request by Nefaro**
This allows to fellow plugins to override the default spawn location and
to override the sky generation.

Related changes
https://github.com/Nefaro/Vanilla/commit/12b198370d22aacb30607ec16a6e8efafee83458
https://github.com/Nefaro/Spout/commit/d0bf803927617ec3a7022c531281878cf7a80a55
https://github.com/Nefaro/SpoutAPI/commit/d266bd3624a57d0ed592fba6aef21c7f29e95c1a
Signed-off-by: Nefaro xsvenson@gmail.com

### CODE REVIEW

**Comment by windy1** [comment]
Could you update this to the current head please? Otherwise, this looks like nothing but in improvements @NinjaZidane :)

**Comment by Nefaro** [comment]
rebased to latest

**Comment by bergerkiller** [comment]
@Nefaro now the flat world generator is gone... :/
Could you rebase and add the general 'if configuration flatworld is true' line back in? It is a requirement for me to test things properly, normal worlds are a pain to debug things in.

**Comment by Nefaro** [comment]
Flat world ? Did I remove flat world ?

**Comment by bergerkiller** [comment]
@Nefaro yes you did...
Yours:
https://github.com/Nefaro/Vanilla/blob/master/src/main/java/org/spout/vanilla/VanillaPlugin.java#L123

Current:
https://github.com/SpoutDev/Vanilla/blob/master/src/main/java/org/spout/vanilla/VanillaPlugin.java#L133

And there's a lot more missing...please do rebase :)

**Comment by Nefaro** [comment]
Yeah, I need to rebase badly, I'll try to finish it tomorrow or the next day. Sry about that.

**Comment by windy1** [comment]
If you are going to rebase this, please take note of the new Sky hierarchy.

**Comment by Salynne** [comment]
I'm going to go ahead and close these. I think it would be much easier for you to just rewrite them and open a new pull request at this point. Sorry for the long wait, I'll be faster about it next time.

**Pull request closed without merging**
