### PR TITLE
Fixes Chiseled Stone Brick texture when placed.

### PR DESCRIPTION
**Pull request by ayyron-dev**
When placing a Chiseled Stone Brick the texture was viewed as a regular Stone Brick. This PR fixes that.

### CODE REVIEW

**Comment by windy1** [comment]
Formatting is off, use tabs not spaces.

**Comment by ayyron-dev** [comment]
I was just told that Netbeans changes tabs to spaces. So that is why that is like that. I'll fix it.

**Comment by lukespragg** [comment]
The commit also needs to be signed off. See http://spout.in/prguide

**Comment by lukespragg** [comment]
Did you mean to close this? :P

**Pull request closed without merging**
