### PR TITLE
Fixed some license comments, added some, implemented VanillaItemMaterial, and a possible fix to redstone!

### PR DESCRIPTION
**Pull request by ZNickq**
I g2g now, sorry if anything is messed up in formatting, etc, will fix it when i get back home this evening! :D

Signed-off by ZNickqteapa011@gmail.com

### CODE REVIEW

**Comment by Afforess** [comment]
Formatting is way off.

**Comment by windy1** [comment]
Spout uses tabs @ZNickq  ;)

**Comment by ZNickq** [comment]
@WalkerCrouse "Use tabs, no spaces." I thought it was the other way around, xD
@Afforess Sorry about that, fixing now ^.^ Tell me when it's in an acceptable form, and i'll merge the commits ;)

**Comment by ZNickq** [comment]
Ok, will re-add the PR in a few minutes, with fixed formatting :P

**Pull request closed without merging**
