### PR TITLE
Added experience/level system to SpoutPlayer. Also, added/modified/implemented several events.

### PR DESCRIPTION
**Pull request by atheriel**
In the process of working on events, I ended up writing an experience/level system into SpoutPlayer. Added an /exp [amount] test command to test it for now. Also added a /poison command to test that.

I also worked on some events, taking Windwalker's advice from the forum.

New events added and implemented:
- PlayerDropItemEvent (partially implemented, waiting for inventories)
- PlayerExperienceChangeEvent
- PlayerGameModeChangeEvent
- PlayerPoisonStatusChangeEvent

Existing/modified events implemented:
- EntityHealthChangeEvent for damage to players
- PlayerBedEvent (renamed PlayerBedInteractionEvent)
- PlayerLevelChangeEvent

New events added but not implemented:
- EntityVehicleInteractionEvent
- LightningStrikeEvent
- PlayerAchievementEvent
- PlayerExperienceChangeEvent
- PlayerHungerChangeEvent
- PlayerPickupItemEvent
- PlayerVillagerTradeEvent
- ProjectileShootEvent

Hope this is helpful. Feedback is appreciated.

### CODE REVIEW

**Comment by atheriel** [comment]
I've just noticed there are some weird Git errors in this.
- I did not modify VanillaPlugin
- The only modifications to TestCommands are at the very end.
- I did not rename PlayerBedEvent PlayerPoisonStatusEvent. I deleted the former and added the latter.

**Comment by lukespragg** [comment]
You have something that isn't respecting the forcing of the line endings it seems, and it's changing the line endings to something else. I wish GitHub had an easier way to see what it's using.

**Comment by atheriel** [comment]
What line endings does Vanilla normally use? I can probably convert them.

**Comment by lukespragg** [comment]
It uses LF in the Git repo, but whatever your system default is locally. First time I've set this up, so not sure how it all performs yet.

**Comment by atheriel** [comment]
I suppose this isn't acceptable for now. Maybe I'll work on it later...

**Pull request closed without merging**
