### PR TITLE
Copy-pasta is bad. We want to sneak, not sprint.

### PR DESCRIPTION
**Pull request by md-5**
BECAUSE I CAN!

### CODE REVIEW

**Comment by ammaraskar** [comment]
:+1:

**Comment by DDoS** [comment]
Sign it off at least...

**Comment by md-5** [comment]
@DDoSQc https://github.com/VanillaDev/Vanilla/pull/419#issuecomment-11405772

> Sign it off at least...

I did.

**Comment by Afforess** [comment]
You do understand that variable names are purely aesthetic, right?

**Comment by md-5** [comment]
@Afforess https://github.com/VanillaDev/Vanilla/pull/419#issuecomment-11413392

> You do understand that variable names are purely aesthetic, right?

Yep. You do understand that JavaDoc is purely aesthetic as well?
It helps to clarify intended behaviour.

**Comment by Afforess** [comment]
> Yep. You do understand that JavaDoc is purely aesthetic as well?

No it's not. It's informative, not aesthetic.

**Pull request merged**
