### PR TITLE
Tree generation

### PR DESCRIPTION
**Pull request by windy1**
Made some normal trees, I attempted birch trees, but <code>VanillaBlocks.birchLog</code> and <code>VanillaBlocks.log</code> seem to be the same at the moment. I also had some encounters with some astray blocks, I don't think it has to do with me and probably the way chunks are loaded.

(The number of commits are due to formatting issues :/)

### CODE REVIEW

**Comment by Afforess** [comment]
Ugh, pulled prematurely. Please sign off on this, and squash the commits into one.

**Comment by Afforess** [comment]
Also the reason why you could not see birch was because chunks are not sending block data yet.

**Comment by windy1** [comment]
@Afforess Err, this is gonna sound kinda dumb but I'm having trouble with the interactive rebase gui. I make my changes, but then where do I go from there and exit the editor?

Like, I don't see any save and close option http://i.imgur.com/boY8I.png

**Comment by windy1** [comment]
Figured it out, see the new pull

**Pull request merged**
