### PR TITLE
More decorators

### PR DESCRIPTION
**Pull request by DDoS**
Finished off some decorators I had started, now I'll start working on the biomes. Maybe I'll have something complete in a month or two.

Signed-off-by: Aleksi Sapon QcTechs@gmail.com

### CODE REVIEW

**Comment by Zidane** [comment]
LOL

**Comment by stephenwilliams** [comment]
y u so LOL

**Comment by DDoS** [comment]
bcuz

"Maybe I'll have something complete in a month or two."

**Comment by RoyAwesome** [comment]
you think that, then you start implementing it and you realize it wasnt that bad

**Pull request merged**
