### PR TITLE
Added sheep meta-data.

### PR DESCRIPTION
**Pull request by spacechase0**
Colored Sheep

Signed-off-by: Chase W chasew@silkweaver.com

### CODE REVIEW

**Comment by windy1** [comment]
We don't want multicolored sheep to spawn by default, only the Vanilla ones. Could you make the color be passed as a parameter through the constructor? Also, your formatting is off.

``` java
public void foo() 
{
    bar.foo();
}
```

Should be 

``` java
public void foo() {
    bar.foo();
}
```

Could you fix these please?

**Comment by spacechase0** [comment]
I keep getting a null pointer exception when trying to do it in the constructor, I guess since `parent` isn't set yet.

``` java
parent.setData("SheepSheared", false);
```

Would a setColor/setSheared method be ok, instead? I'll make it default to white in `onAttached()`.

**Comment by windy1** [comment]
Don't actually set it in the constructor, set a variable for later use

``` java
private final int color;

public Sheep(int color) {
    this.color = color;
}

@Override
public void onAttached() {
    // blah blah blah
    parent.setData("SheepColor", color));
}
```

Would be nice if you could overload the constructor as well so no args can be given for a white sheep.

**Comment by spacechase0** [comment]
Oh, ok.

**Comment by spacechase0** [comment]
Done.

Hope I didn't miss any more formatting stuff. :P

**Pull request merged**
