### PR TITLE
Adds last damager and damage cause to VanillaEntityDeathEvent and PlayerDeathEvent

### PR DESCRIPTION
**Pull request by timmhirsens**
Signed-off-by: fr1zle f@br0tbox.de

### CODE REVIEW

**Comment by Sleaker** [comment]
lastDamager needs to be more type-specific than an object. having it so unspecific doesn't make the API friendly to plugins, this may have been why nothing was implemented yet.

**Comment by dredhorse** [comment]
Problem is I think that there are a lot of different damagers... minecarts, cactus, lava, player, mobs etc..

I don't really know a good solution to this though myself, except perhaps having lastDamageCause handle it, together with an enum which exposes the damager. On the other side that makes it problematic to extend.

**Comment by windy1** [comment]
@Sleaker @dredhorse is right, I don't see any nicer way to do it, no matter how you implement it you will always have to cast something.

**Comment by Sleaker** [comment]
@W1ndwaker - then putting the Damager on the Cause is the best way to handle this, rather than making it accessible directly.

Providing a method that returns an Object does no good as there's no functional way to tell what it is without performing a considerable number of checks, and even then you can't be certain what you're getting out.

**Comment by timmhirsens** [comment]
It is the same in EntityDamageEvent. This is of course not a good solution but I really wouldn't know how to handle it different / better.
Only exposing it in DamageCause doesn't really change anything imho, since its just one method call more.

**Comment by windy1** [comment]
@Sleaker 

What's so complicated about.

``` java
Object lastDamager = event.getLastDamager();
if (lastDamager instanceof Player) {
    Player player = (Player) lastDamager;
    // last damager is a player
}
```

Do you have a simpler solution?

**Pull request merged**
