### PR TITLE
Explosion Resistance & 1.2 Blocks

### PR DESCRIPTION
**Pull request by Owexz**
Signed-off-by: Owexz owexz@owexz.net

### CODE REVIEW

**Comment by Zidane** [comment]
I hate to be a pain but I need you to sign it off.

aka...

Signed-off by: Owexz<emailhere>

you can also do git commit -s as well...make sure you keep it as one commit when you fix it.

**Comment by Owexz** [comment]
Signed off, yes I know there's a lot of Owexz in there, I'm just egotistical :p

**Comment by Zidane** [comment]
Thanks for the contribution!

**Comment by Owexz** [comment]
No worries, I've figured out how to use git properly now, so it was useful for me as well

**Comment by Zidane** [comment]
uh oh...something broke :p

**Comment by Zidane** [comment]
http://ci.spout.org/job/Vanilla/540/console

**Comment by Owexz** [comment]
Found the error:
public static final BlockMaterial WEB = new Solid("Cobweb",30).setHardness(4.0F).setResistance(20F.setResistance(0.1F));
I've accidentally duplicated web's resistance values, expect fix soon.

**Pull request merged**
