### PR TITLE
Added Teleport Command

### PR DESCRIPTION
**Pull request by emericask8ur**
Vanilla Command

/Teleport [Player] [Player]

Signed-off-by: emericask8ur sk8tj@yahoo.com

### CODE REVIEW

**Comment by lukespragg** [comment]
Not to mention the title casing when none of the previously implemented commands use that... :P

**Comment by ZNickq** [comment]
Also, this is already implemented...

**Comment by windy1** [comment]
Yeah, I believe I added a tp command a while back, if not in SpoutAPI yet. :p

**Comment by Zidane** [comment]
Closing this...already implemented.

**Pull request closed without merging**
