### PR TITLE
Block Explosion Resistance and Light values added, 1.2 block added.

### PR DESCRIPTION
**Pull request by Owexz**

### CODE REVIEW

**Comment by Afforess** [comment]
Fix the formatting.

**Comment by Owexz** [comment]
Fixed it, tell me if I've missed anything, I had to copy paste to github from eclipse, the school proxy blocks me uploading commits.

**Comment by windy1** [comment]
Update to current HEAD please :)

**Comment by Zidane** [comment]
Indeed...squash your commits and rebase to the HEAD please :).

**Comment by Owexz** [comment]
Will do once I get home, school finishes in 10 mins.

**Comment by Owexz** [comment]
Squashed it

**Comment by windy1** [comment]
Still needs to be updated to the current HEAD

<code>git remote add upstream git@github.com:SpoutDev/Vanilla.git
git fetch upstream
git merge upstream/master
git push origin master</code>

**Comment by Owexz** [comment]
Closing request, due to an error with Git, I've reforked Vanilla and I'll add the code into that and submit a new request.

**Pull request closed without merging**
