### PR TITLE
I added online mode

### PR DESCRIPTION
**Pull request by ezruneko**

### CODE REVIEW

**Comment by ZNickq** [comment]
Looks good, but you completely changed the formatting of one of the files :P

**Comment by Raphfrk** [comment]
The first file should have minimum changes.

However, we already supported online mode.

```
public static final ConfigurationHolder ONLINE_MODE = new ConfigurationHolder(true, "general", "online-mode");
```

**Comment by ezruneko** [comment]
I use eclipse on windows so he changes \r\n :(

"However, we already supported online mode.". How? i dont see it on any configuration file.

**Comment by Raphfrk** [comment]
The parameter is the one I quoted.

Also, online mode is handled by the packets accepting the handshake:

https://github.com/VanillaDev/Vanilla/blob/master/src/main/java/org/spout/vanilla/protocol/bootstrap/handler/BootstrapHandshakeMessageHandler.java

**Comment by Raphfrk** [comment]
One thing it doesn't support is offline and encryption mode.  However, I am not sure what that would achieve.

It would prevent the server from verifying that a user is who they claim to be.  A trusting server like that isn't going to benefit from encrypting the connection much.

**Comment by stephenwilliams** [comment]
Raphfrk you can delete and edit posts

**Comment by Raphfrk** [comment]
Thanks, not sure what is happening here, looks like my browser won't auto-update, when I comment.

**Comment by Zidane** [comment]
Already in

**Pull request closed without merging**
