### PR TITLE
Fix WindowClickMessage and update for almost all inventory features for 1.5 changes 

### PR DESCRIPTION
**Pull request by kitskub**
The only feature not in this is number 5 in this video: http://www.youtube.com/watch?v=iZD5pJ2uIVM

Signed-off-by: Jack Huey kitskub@gmail.com

### CODE REVIEW

**Comment by Zidane** [comment]
Great commit but I have one little quirk with it.

Can you not use bytes (like for getClickArguments) and instead use enums? From API perspective, bytes are rather unfriendly...

Also could you catch up the javadocs entirely for windows while you are at it? Thanks :).

**Comment by kitskub** [comment]
Ok, I'll do that.

**Comment by kitskub** [comment]
I updated for the enum. Not sure what javadocs in particular you're thinking about. They seem pretty well documented.

**Comment by windy1** [comment]
I believe he is asking you to document the enum. Conventional way to do this is.

``` java
/**
 * Description of foo
 **/
enum Foo {
    /**
     * Description
     **/
    BAR;
    /**
     *
     **/
    BAZ;

    // then document as you would a class
}
```

e: when I was quickly reading @Zidane 's comment I didn't see he was referring to Windows. Documentation for the enum would still be nice though.

**Comment by Zidane** [comment]
I was talking about the javadocs for the Windowing System in Vanilla (in-general).

That can be another commit, thanks!

**Pull request merged**
