### PR TITLE
Update Recipes List

### PR DESCRIPTION
**Pull request by SonarBeserk**
Recipes list for the Vanilla plugin.

### CODE REVIEW

**Comment by kitskub** [comment]
http://www.minecraftwiki.net/wiki/Crafting
That is the complete recipe list.
Also, the commits need to be squashed.

**Comment by SonarBeserk** [comment]
latest commit is the current one.
@kitskub i need you to confirm the name for the slabs. and most likely stairs so i can complete it. What Result do i need to return for those?

**Comment by kitskub** [comment]
I just looked at slabs, but they are in the form of type slab, (i.e. sandstone slab). You can check it in material/block/misc. And again, these need to be a single commit. It is showing three different ones.

**Comment by Salynne** [comment]
There was another pull that was more correct and already done so closing this. Thanks though.

**Comment by SonarBeserk** [comment]
my question is if it was done why is the recipes so out of date?

**Comment by Afforess** [comment]
The recipes seem up to date to me: https://github.com/VanillaDev/Vanilla/blob/master/src/main/resources/recipes.yml

**Comment by SonarBeserk** [comment]
they wernt before. they are now. so it is finished.

**Pull request closed without merging**
