### PR TITLE
Added missing entity protocol.

### PR DESCRIPTION
**Pull request by Cybermaxke**

### CODE REVIEW

**Comment by kitskub** [comment]
Can you verify this is still good?

@zidane we should merge this

**Comment by Cybermaxke** [comment]
I think that it is still working, only 'getDatatable' -> 'getData'

**Comment by kitskub** [comment]
Yeah, getDatatable() needs to be changed to getData().

If you fix that, I'll merge it on review.

**Comment by Cybermaxke** [comment]
Ok, done. ;)

**Comment by kitskub** [comment]
@Zidane PR looks good to me, I'm going to go ahead and merge.

**Pull request merged**
